version: 2

jobs:
  build:
    docker:
      - image: circleci/node:9.9.0-stretch
    working_directory: ~/app
    parallelism: 1
    steps:
      - checkout:
          path: ~/app
      - run: sudo apt-get update && sudo apt-get install -y bash bats shellcheck
      - run:
          name: Running tests
          command: bats emojify_tests.bats
      - run:
          name: Running Shellcheck
          command: shellcheck --exclude=SC1117 emojify
